name: Windows Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.13.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          go build -v -a -o ./bin/csi-proxy.exe ./cmd/csi-proxy
      - name: Run Windows Unit Tests
        run: |
          go test -v -race ./internal/...
      - name: Run Windows Integration Tests
        run: |
          # start the CSI Proxy before running tests on windows
          Start-Job -Name CSIProxy -ScriptBlock {
            .\bin\csi-proxy.exe --kubelet-csi-plugins-path $pwd --kubelet-pod-path $pwd
          };
          Start-Sleep -Seconds 30;
          Write-Output "getting named pipes"
          [System.IO.Directory]::GetFiles("\\.\\pipe\\")

          go test -v -race ./integrationtests/volume_test.go ./integrationtests/filesystem_test.go ./integrationtests/disk_test.go
